### ISSUE TITLE
ในแต่ละ flow ยังไม่มีเรื่องของ technical

### ISSUE THREAD

**Issue by up1** [pspapleng/Project-SW-dev-tool-env-14#1]
- ในแต่ละ  flow ต้องมี technical แยกกัน ไม่ควรรวมกัน
- ในการแตก task นั้น ต้องเอาไปใส่ใน project management tools ที่ทีมต้องลงร่วมกันที่จะใช้คือ Jira แล้ว invite ผมเข้าไป join ด้วย

**Comment by ApichaJA** [comment]
เพิ่ม Technical ในแต่ละ Flow ให้แล้วครับ และ Invite อาจารย์เข้า Jira เรียบร้อยแล้วครับ
